apiVersion: v1
data:
  api-definition: |
    {
    "name": "api",
    "slug": "api",
    "api_id": "3",
    "org_id": "1",
    "definition": {
      "location": "header",
      "key": "x-api-version"
    },
    "use_keyless": true,
    "version_data": {
      "not_versioned": true,
      "versions": {
        "Default": {
          "name": "Default",
          "use_extended_paths": true
        }
      }
    },
    "proxy": {
      "listen_path": "/api/",
      "target_url": "http://api-service:1337",
      "strip_listen_path": true
    },
    "active": true
    }
  client-definition: | 
    {
    "name": "app",
    "slug": "app",
    "api_id": "2",
    "org_id": "1",
    "definition": {
      "location": "header",
      "key": "x-api-version"
    },
    "use_keyless": true,
    "version_data": {
      "not_versioned": true,
      "versions": {
        "Default": {
          "name": "Default",
          "use_extended_paths": true
        }
      }
    },
    "proxy": {
      "listen_path": "/",
      "target_url": "http://ui-service:3000",
      "strip_listen_path": true
    },
    "active": true
    }

  
kind: ConfigMap
metadata:
  name: tyk-gateway-conf
